#%RAML 1.0 NamedExample

value:

  - 
    ID: "1"
    firstName: Srishti
    lastName: Jain
    address: shahdara
    postal: 110032
    country: India
    miles: 332
    creationDate: 2019-11-16T10:00:00-05:00 
    AccountType: Business
  
  -
    ID: "2"
    firstName: Srish
    lastName: Jain
    address: shahdara Delhi
    postal: 110031
    country: India
    miles: 347
    creationDate: 2019-02-13T10:00:00-05:00 
    AccountType: Personal